### ISSUE TITLE
Can't sync starship 

### ISSUE THREAD

**Issue by slyshykO** [chshersh/tool-sync#116]
https://github.com/starship/starship/releases

```toml
[starship] 
owner = "starship"
repo = "starship"
exe_name = "starship"
asset_name.windows = "starship-x86_64-pc-windows-msvc.zip"
```

```sh
>tool sync
x  starship
Multiple name matches found for this asset:

         * starship-x86_64-pc-windows-msvc.zip
         * starship-x86_64-pc-windows-msvc.zip.sha256

Please add one of these to the config.
```
