### ISSUE TITLE
Support executables that aren't in an archive

### ISSUE THREAD

**Issue by binyomen** [chshersh/tool-sync#138]
I'm thinking this would be useful for repos like [marksman](https://github.com/artempyanykh/marksman/releases) which store the executables as top-level assets rather than in archives.

Thanks! I was about to make this tool myself when I saw someone had just recently started it!

**Comment by chshersh** [comment]
@binyomen That sounds like a good idea! `tool-sync` already supports `.exe` executables on Windows that aren't in the archive.

* https://github.com/chshersh/tool-sync/blob/5d1a6b6010ca44ec81571c4d7b677c3cb01bb6cd/src/sync/archive.rs#L67-L75

But it makes sense to support them from other platforms as well 🙂

**Comment by binyomen** [comment]
Huh, weird, that doesn't seem to work for me. With the config:

```toml
store_directory = '~/bin'

[marksman]
owner = 'artempyanykh'
repo = 'marksman'
asset_name.windows = 'marksman.exe'
```

I get the output:

```
🔄  All done!
📦  Estimated total download size: 16.93 MiB
⛔  marksman 2022-09-13 [error] The system cannot find the file specified. (os error 2)                                 ✨  Successfully installed 0 tools!
📁  Installation directory: C:\Users\beweedon/bin
```
