### ISSUE TITLE
Add the 'version' field in TOML

### ISSUE THREAD

**Issue by chshersh** [chshersh/tool-sync#68]
This field is an alternative to the `tag` field (so it should be an error to specify both of them).

This field should support more flexible version matching of tags while the `tag` field supports tags **exactly**. With `version,` it should be possible to specify the following:

```toml
version = "latest"  # uses exactly the latest version
version = "13.0.0"  # matches both tags 'v13.0.0' and '13.0.0' so you don't need to know the naming scheme of a particular repository
version = "13"      # should automatically download the latest minor version matching '13.*.*'
```

See the following issue for more context:

* https://github.com/chshersh/tool-sync/issues/65
