### ISSUE TITLE
Add checksum check

### ISSUE THREAD

**Issue by chshersh** [chshersh/tool-sync#70]
Adding checksum check (SHA256 or MD5) would enable two features:

* Avoiding the downloading if checksum didn't change
* Verifying the exact matching version

The current problem with supporting this feature is that GitHub doesn't provide this information in their API and maintainers usually don't include the checksum either. One example of a package that has checksum is GitHub CLI:

* https://github.com/cli/cli/releases/tag/v2.15.0

So, first, we need to figure out how to get the reliable source of checksum.

**Comment by MitchellBerend** [comment]
Is there a reason the tool should not just check all the files in the release for a `sha` or `md` sub string? There is a small discussion about requesting the feature [here](https://github.com/orgs/community/discussions/16426). I think we can just support this feature for repos that do publish a checksum.

I would add an optional option in the `tool.toml` like this.

```toml
# This configuration is automatically generated by tool-sync 0.2.0
# https://github.com/chshersh/tool-sync
#######################################
#
# Installation directory for all the tools:
store_directory = "$HOME/rust/tool-sync/bin"
#
# tool-sync provides native support for some of the tools without the need to
# configure them. Uncomment all the tools you want to install with a single
# 'tool sync' command:
#
# [bat]
# [difftastic]
# [exa]
# [fd]
# [github]
# [ripgrep]
# [tool-sync]
#
# You can configure the installation of any tool by specifying corresponding options:
#
[ripgrep]  # Name of the tool (new or one of the hardcoded to override default settings)
    owner     = "BurntSushi"  # GitHub repository owner
    repo      = "ripgrep"     # GitHub repository name
    exe_name  = "rg"          # Executable name inside the asset

    checksum  = "some_checksum_string"
#     Uncomment to download a specific version or tag.
#     Without this tag latest will be used
#     tag       = "13.0.0"

#     Asset name to download on linux OSes
    asset_name.linux = "musl"

#     Uncomment if you want to install on macOS as well
#     asset_name.macos = "apple-darwin"

#     Uncomment if you want to install on Windows as well
#     asset_name.windows = "x86_64-pc-windows-msvc"
```
